### PR TITLE
Add function to toggle M236 pressure multiplier

### PR DESCRIPTION
**Pull request by sean-v8**
## M222 - Enable/disable pressure multiplier

The pressure multiplier I added in d4ee119 results in multiplication of both the active tool's extrusion values as well as any pressures set via `M236`... not normally an issue for FFF or silver, but for the auger tool we'd like to be able to scale extrusion linearly without affecting the system pressure.

(multiplier enabled by default, `M222` or `M222 S255` to enable, `M222 S0` to disable)

### CODE REVIEW

**Comment by sean-v8** [comment]
Switched Pompous Pumpkin to a pneumatics sled for testing, behaving as expected.

@kdumontnu @danthompson41 @jminardi @pizzyflavin

**Comment by danthompson41** [comment]
Looks good to me. It'd be preferable to throw it in the Gcodes.h file that we're using for all new mcodes but if you want to leave it here I won't hold it against you.

**Comment by sean-v8** [comment]
Yeah I felt it was a little clearer to leave it as close to M221 as possible and keep the boolean declared in the same file, I'm cool with whatever you guys think is best though.

**Comment by danthompson41** [comment]
Works for me for the moment. Merge it in if you feel confident

**Pull request merged**
