### PR TITLE
Added Z tool offset

### PR DESCRIPTION
**Pull request by Lucky1313**
Added Z offset option, tested using the M218 code

### CODE REVIEW

**Comment by jminardi** [comment]
Was this tested on the actual printer?

**Comment by Lucky1313** [comment]
No, what would be the best way to test this on a printer? The auto-alignment script?

**Comment by jminardi** [comment]
Connect to the printer and send the tool offset command for both tools including x, y, and z. Then  activate tool 0, move to a position, activate tool 1 and call abs move to that same position. You should see the head move in x, y and z

**Comment by Lucky1313** [comment]
Verified working on the printer.

**Pull request merged**
