### PR TITLE
Handle paths with spaces and adjust _Version.h generation

### PR DESCRIPTION
**Pull request by kevingelion**
This is so that people who have spaces in their Windows usernames.

This gives more control of the different parts of the version file such as numeric version, commit number, and hash all as separate variables.

### CODE REVIEW

**Comment by dreammaker** [comment]
What happens if you run this script from another directory?  `pwd` isn't necessarily the script's directory.

**Comment by kevingelion** [comment]
I was under the assumption that it would always be run from the scripts directory. Wouldn't it be difficult to know where the Marlin folder is for anyone using it?

**Comment by dreammaker** [comment]
[Can a Bash script tell what directory it's stored in?](http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in)

**Comment by kdumontnu** [comment]
Does not work on my computer. 

I get:

`cp: cannot stat `/c/Users/Kyle\\ Dumont/Documents/Firmware/Marlin/ArduinoAddons/
Arduino_1.6.x/hardware/marlin/avr/boards.txt': No such file or directory`

I changed `HERE=$(echo $HERE | sed 's/ /\\ /g')` to `HERE=$(echo $HERE | sed 's/ /\ /g')` and then I get the same error we had before: "must load at least one sketch file"

**Comment by kevingelion** [comment]
The issue is the way the space in your username is being handled - making bash thing the stuff after the space is a new argument. The backslash was added to escape the space. I'll fix on Monday though I thought that would have fixed it.

**Comment by kevingelion** [comment]
This is ready and tested!

**Comment by jminardi** [comment]
Thanks!

**Pull request merged**
