### PR TITLE
D/feature pause

### PR DESCRIPTION
**Pull request by Lucky1313**

### CODE REVIEW

**Comment by jminardi** [comment]
You also need to bring in the definition of `RESUME_PIN` here.

**Comment by Lucky1313** [comment]
It's in pins.h

**Comment by jminardi** [comment]
Ah I have no idea how I missed that. Can you test this before merging?

**Comment by Lucky1313** [comment]
What would be the best way to test this?

**Comment by jminardi** [comment]
Get a button, connect it between Pin 24 and Ground, send M399 then G1 X10 and see if the move is only executed after the button is pressed

**Comment by Lucky1313** [comment]
Pause verified to be working.

**Comment by jminardi** [comment]
OK, merge when ready

**Pull request merged**
